# Generated by Django 4.0.3 on 2022-05-25 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejscowosc', models.CharField(max_length=50)),
                ('ulica', models.CharField(blank=True, max_length=50, null=True)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('numer_domu', models.CharField(max_length=5)),
                ('numer_lokalu', models.IntegerField(blank=True, null=True)),
                ('imie', models.CharField(blank=True, max_length=50, null=True)),
                ('nazwisko', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresy',
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_urodzenia', models.DateField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=9, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
            },
        ),
        migrations.CreateModel(
            name='Opinie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentarz', models.CharField(max_length=400)),
                ('ocena', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Podkategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=9)),
                ('opis', models.CharField(blank=True, max_length=500)),
                ('ilosc_dostepnego', models.PositiveIntegerField()),
                ('opinie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.opinie')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='RodzajePlatnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rodzaje Platnosci',
                'verbose_name_plural': 'Rodzaje Platnosci',
            },
        ),
        migrations.CreateModel(
            name='RodzajWysylki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rodzaj Wysyłki',
                'verbose_name_plural': 'Rodzaje Wysyłki',
            },
        ),
        migrations.CreateModel(
            name='Zdjecia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdjecie', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zamowienia', models.DateField()),
                ('data_wyslania', models.DateField()),
                ('data_dostarczenia', models.DateField()),
                ('czy_oplacono', models.BooleanField()),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.adres')),
                ('klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.klient')),
                ('produkt', models.ManyToManyField(to='sklep.produkt')),
                ('rodzaj_wysylki', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.rodzajwysylki')),
            ],
            options={
                'verbose_name': 'Zamówienie',
                'verbose_name_plural': 'Zamówienia',
            },
        ),
        migrations.AddField(
            model_name='produkt',
            name='zdjecie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.zdjecia'),
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_urodzenia', models.DateField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=9, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.CreateModel(
            name='Platnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data_zaksiegowania', models.DateTimeField()),
                ('rodzaj_platnosci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.rodzajeplatnosci')),
                ('zamowienie', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.zamowienie')),
            ],
            options={
                'verbose_name': 'Płatności',
                'verbose_name_plural': 'Płatności',
            },
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('podkategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.podkategoria')),
            ],
        ),
        migrations.AddField(
            model_name='adres',
            name='klient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.klient'),
        ),
        migrations.AddField(
            model_name='adres',
            name='pracownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.pracownik'),
        ),
    ]
