# Generated by Django 4.0.3 on 2022-06-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rozmiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rozmiar', models.CharField(max_length=5)),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.produkt')),
            ],
            options={
                'verbose_name': 'Rozmiar',
                'verbose_name_plural': 'Rozmiary',
            },
        ),
    ]
