# Generated by Django 4.0.3 on 2022-05-31 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienie',
            name='produkt',
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='data_dostarczenia',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='data_wyslania',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='PozycjaZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField()),
                ('czy_zamowiony', models.BooleanField(default=False)),
                ('data_dodania', models.DateTimeField(auto_now=True)),
                ('data_zamowienia', models.DateTimeField(null=True)),
                ('produkt', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklep.produkt')),
            ],
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='pozycje_zamowienia',
            field=models.ManyToManyField(to='sklep.pozycjazamowienia'),
        ),
    ]
