# Generated by Django 4.0.4 on 2022-05-27 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Podkategorie'},
        ),
        migrations.AlterModelOptions(
            name='opinie',
            options={'verbose_name': 'Opinia', 'verbose_name_plural': 'Opinie'},
        ),
        migrations.AlterModelOptions(
            name='podkategoria',
            options={'verbose_name': 'Podkategoria', 'verbose_name_plural': 'Podkategorie'},
        ),
        migrations.AlterModelOptions(
            name='zdjecia',
            options={'verbose_name': 'Zdjecie', 'verbose_name_plural': 'Zdjecia'},
        ),
        migrations.RemoveField(
            model_name='adres',
            name='pracownik',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='opinie',
        ),
        migrations.AddField(
            model_name='opinie',
            name='klient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sklep.klient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opinie',
            name='produkt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.produkt'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='podkategoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sklep.podkategoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zdjecia',
            name='zdjecie',
            field=models.ImageField(upload_to='produkty'),
        ),
    ]
