# Generated by Django 4.0.4 on 2022-06-19 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategoria',
            name='podkategoria',
        ),
        migrations.AddField(
            model_name='podkategoria',
            name='kategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.kategoria'),
        ),
    ]
