# Generated by Django 4.0.3 on 2022-06-12 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_rozmiar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='ilosc_dostepnego',
        ),
        migrations.RemoveField(
            model_name='rozmiar',
            name='produkt',
        ),
        migrations.CreateModel(
            name='Produkt_Rozmiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_dostepnego', models.PositiveIntegerField()),
                ('produkt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.produkt')),
                ('rozmiar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.rozmiar')),
            ],
        ),
    ]
