# Generated by Django 4.0.4 on 2022-06-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_remove_kategoria_podkategoria_podkategoria_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='numer_lokalu',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
