# Generated by Django 4.0.3 on 2022-05-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_remove_zamowienie_produkt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='czy_zamowione',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='czy_oplacono',
            field=models.BooleanField(default=False),
        ),
    ]
