# Generated by Django 4.0.3 on 2022-06-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0003_remove_produkt_ilosc_dostepnego_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycjazamowienia',
            name='rozmiar',
            field=models.IntegerField(null=True),
        ),
    ]
