# Generated by Django 4.0.3 on 2022-05-31 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0003_zamowienie_czy_zamowione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zamowienie',
            name='adres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.adres'),
        ),
    ]
