# Generated by Django 4.0.3 on 2022-06-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0005_kartyplatnicze'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platnosci',
            name='data_zaksiegowania',
            field=models.DateTimeField(null=True),
        ),
    ]
