# Generated by Django 4.0.3 on 2022-06-02 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0006_alter_platnosci_data_zaksiegowania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pozycjazamowienia',
            name='produkt',
        ),
        migrations.AddField(
            model_name='produkt',
            name='pozycja_zamowienia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklep.pozycjazamowienia'),
        ),
    ]
