# Generated by Django 4.0.4 on 2022-06-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0008_remove_produkt_pozycja_zamowienia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kartyplatnicze',
            options={'verbose_name': 'Karta Płatnicza', 'verbose_name_plural': 'Karty Płatnicze'},
        ),
        migrations.AlterModelOptions(
            name='pozycjazamowienia',
            options={'verbose_name': 'Pozycja zamówienia', 'verbose_name_plural': 'Pozycje zamówień'},
        ),
    ]
